### ISSUE TITLE
llvm module

### ISSUE THREAD

**Issue by kangyan0902** [paperswithcode/axcell#11]
I have encountered the following error while reproducing the result from evaluation.ipynb:
ModuleNotFoundError: No module named 'llvm'
More errors were generated while finishing up the installation and setup. I’m currently stucked with this step. After a thorough searching, I also figured that llvmpy is a relative old module. Hence, I’m wondering if there is any required settings for this part. Or, do you have any idea of how to resolve this issue.

**Comment by mkardas** [comment]
Hi, what platform are you running on? Can you create a new conda environment (using the updated `environment.yml`) and post the errors? `llvm` is not our direct dependency, it's used by `numba`. You can try to install `numba` using `pip` instead of `conda`.
