### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by Charlotte-Yiyao-CHEN** [paperswithcode/axcell#13]
Hi, as for the three datasets you are using (ArxivPapers, SegmentedTables & LinkedResults, PWCLeaderboards), are the three data files involved in the notebooks (arxiv-papers.csv.xz, segmented-tables.json.xz, pwc-leaderboards.json.xz) all that we need necessary? Do we need to manually download each paper using the get_eprint_link(paper) function in the datasets notebook? If so, it would be great if a zip file for all papers can be provided.

In addition, I have looked into the paper_collection.py, where many .json files needed but not provided neither. Could you give some guidance about how to get those files as well?

**Comment by Charlotte-Yiyao-CHEN** [comment]
For example, how do we find the "structure-annotations.json", which is involved in the paper_collection.py?

**Comment by mkardas** [comment]
Hi,

all the data is present except for the archived papers sources. As noted in the [datasets notebook](/paperswithcode/axcell/tree/master/notebooks/datasets.ipynb):

> Due to the licensing the datasets consists of metadata and annotations, but do not include papers and data extracted from them. However, we made special effort in our extraction pipeline to get reproducible results.

To get the papers you can download them or in the case of the large ArxivPapers dataset, use arXiv's S3 bucket (see [this script](/paperswithcode/axcell/tree/master/scripts/download_arxiv_s3_papers.sh)). The large dataset is used mainly to pre-train a language model, so if you can use the language model we published you don't need the dataset (see [lm notebook](/paperswithcode/axcell/tree/master/notebooks/training/lm.ipynb) for details).

"structure-annotations.json" is no longer needed, as it's an older format that was used to store SegmentedTables and LinkedResults. You can load annotations directly from SegmentedTables, see [table-segmentation notebook](/paperswithcode/axcell/tree/master/notebooks/training/table-segmentation.ipynb) on how to do it.
