### ISSUE TITLE
permission denied of latex2html.sh

### ISSUE THREAD

**Issue by GabrielLin** [paperswithcode/axcell#14]
When I run the `extraction.ipynb`. I am facing the following issues:
```
docker.errors.APIError: 400 Client Error: Bad Request ("OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/files/latex2html.sh\": permission denied": unknown")
```

I can run docker without sudo and can successfully run the following sample using docker-py
```
import docker
client = docker.from_env()
```

```
>>> client.containers.run("ubuntu:latest", "echo hello world")
'hello world\n
```

Could you help? Thanks.

**Comment by GabrielLin** [comment]
I have already run
```
docker pull arxivvanity/engrafo:b3db888fefa118eacf4f13566204b68ce100b3a6

```

**Comment by mkardas** [comment]
Hi Gabriel,

can you verify with `ls -l axcell/scripts/latex2html.sh` that the file has the execute permissions correctly set?

**Comment by GabrielLin** [comment]
> Hi Gabriel,
> 
> can you verify with `ls -l axcell/scripts/latex2html.sh` that the file has the execute permissions correctly set?

Dear @mkardas ,
Thanks for your rapid reply. How stupid I am. I thought the issue was caused by docker and just checked everything about docker. The issue has been fixed and the extraction step has been successfully done.

**Comment by yafangwang9** [comment]
I change the permissions  of this file :cell/scripts/latex2html.sh 
Now run ls -l axcell/scripts/latex2html.sh , got this：-rwxr-xr-x 1 jacinthewyf jacinthewyf 1056 6月  23 21:52 axcell/scripts/latex2html.sh

But it always got this information :container_linux.go:380: starting container process caused "exec: \"/files/latex2html.sh\": permission denied": unknown")

What should I do to solve this? Looking forward to your reply.

**Comment by mkardas** [comment]
Hey, can you temporarily change `scriptname` in https://github.com/paperswithcode/axcell/blob/f4648d8fee1aa8482d007a38828da9dc06630f0e/axcell/helpers/latex_converter.py#L37 to `ls -l /files/` and rerun to verify permissions as seen from the container?

**Comment by yafangwang9** [comment]
> Hey, can you temporarily change `scriptname` in
> 
> https://github.com/paperswithcode/axcell/blob/f4648d8fee1aa8482d007a38828da9dc06630f0e/axcell/helpers/latex_converter.py#L37
> 
> to `ls -l /files/` and rerun to verify permissions as seen from the container?

Hi~thank you very much for your reply! I try it.
