### ISSUE TITLE
'LSTM' object has no attribute '_flat_weights_names'

### ISSUE THREAD

**Issue by samokhinv** [paperswithcode/axcell#15]
Hi!

After successfully setting up the conda environment, I tried to run [`result-extraction.ipynb`](https://github.com/paperswithcode/axcell/blob/master/notebooks/results-extraction.ipynb) notebook. Unfortunately, I faced the following error `'LSTM' object has no attribute '_flat_weights_names'` while loading the 'ResultsExtractor'. 

Have I done something wrong or missed some requirements/dependencies?

**Comment by mkardas** [comment]
Hi,

it looks like version mismatch between pytorch and fastai. Can you post the result of running:
```python
from fastai.utils.show_install import *
show_install()
```
