### ISSUE TITLE
Docker Requirement?

### ISSUE THREAD

**Issue by kochbj** [paperswithcode/axcell#17]
Hi all,

Super cool tool; thanks for making this! I was wondering if I could get a liitle more information about how Docker is used and whether it is possible to get around the Docker requirement (e.g., to run axcell in Colab). My best guess is that it is creating extra nodes for elasticsearch?

Thanks for your time,
Bernie

**Comment by mkardas** [comment]
Hi Bernie,

glad to know that you like the project. As you noticed, one reason we use docker is to easily spin-up an elasticsearch instance, which is used in the table segmentation step. Additionally, we use docker to run LaTeX to HTML conversion with [engrafo](https://github.com/arxiv-vanity/engrafo) container. If you can setup both of them in Colab you should be able to run the pipeline. For elasticsearch you just need to update [the config](https://github.com/paperswithcode/axcell/blob/095422a6c35ad1750cd35a4cb0c126a61f8ee3eb/axcell/config.py#L18). For engrafo you have to modify [latex_converter](https://github.com/paperswithcode/axcell/blob/095422a6c35ad1750cd35a4cb0c126a61f8ee3eb/axcell/helpers/latex_converter.py) to use a local instance.

**Comment by kochbj** [comment]
Thanks Marcin, this is super helpful. I'll fool around with it. :)
