### ISSUE TITLE
ConnectionError when calling arxiv-vanity/engrafo

### ISSUE THREAD

**Issue by ZhiruoWang** [paperswithcode/axcell#18]
Hi, I really appreciate this work and am trying to reproduce the results. 
However, I failed to perform the extraction, even from a single e-print archive for paper 1903.11816v1. To be more specific, when the LatexConverter is calling the arxiv-vanity/engrafo api (at line 65 of latex_converter.py), it reports:
Exception has occurred: ConnectionError
('Connection aborted.', PermissionError(13, 'Permission denied'))
  File "/mnt/zr/axcell/axcell/helpers/latex_converter.py", line 65, in latex2html
    self.client.containers.run("arxivvanity/engrafo:b3db888fefa118eacf4f13566204b68ce100b3a6", command, remove=True, volumes=volumes)
  File "/mnt/zr/axcell/axcell/helpers/latex_converter.py", line 84, in to_html
    self.latex2html(source_dir, output_dir)
  File "/mnt/zr/axcell/axcell/helpers/paper_extractor.py", line 41, in __call__
    html = self.latex.to_html(unpack_path)

Could you share some ways to resolve this problem? Thanks very much!

**Comment by mkardas** [comment]
Hi @ZhiruoWang,

sorry for the late answer, I totally missed your report. Can you check if you can:
* run docker containers without `sudo` (see https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user on how to configure it if you cannot)?
* run any docker container at all from python (see for example code snippets in the first message of https://github.com/paperswithcode/axcell/issues/14)?
