### ISSUE TITLE
AxCell CondaEnv. creation fails on Windows

### ISSUE THREAD

**Issue by Relaxi0n** [paperswithcode/axcell#19]
Hey,

I am planing to further elaborate and implement features for AxCell. However unfortunately I do not own a Linux or Mac OS. While trying to install AxCell on Windows10 i ran into some issues. When im trying to install the Conda Enviroment (using Anaconda  3.8 Python) via the presented file, "magic_python" and "docker-compose" seem to be only available for Linux/MacOs. 

Is it possible to run AxCell on Windows?

**Comment by mkardas** [comment]
Hi,

we haven't tried running AxCell on Windows so I have no idea how much effort would be required to do it. The easiest way for local development on Windows would be to run Linux on Virtual Machine (f.e., using VirtualBox) or Windows Subsystem for Linux (again, haven't tried those options).

We use `magic_python` to detect file type as by default the e-print files returned by arXiv have no extensions. There are only couple cases that need to be covered (mostly: gzipped TAR archive with .tex source, gzipped single source .tex file, PDF or plaintext txt file), so you could possibly handle them without `magic_python` (doable, but not the most pleasant way to spend your time) or try to find a Windows alternative of the package (I guess it's only Linux/MacOS as it's a thin wrapper over `magic` command / `libmagic` library).

`docker-compose` is added to requirements for convenience, you can install it on Windows separately and remove from the dependencies.

Keep in mind that even if you solve these two issue I have no idea how many are ahead of you.

**Comment by Relaxi0n** [comment]
Thank you for the quick and informative response.
