### ISSUE TITLE
Steps to run replicate the full code on windows.

### ISSUE THREAD

**Issue by purnasrivatsa96** [paperswithcode/axcell#22]
Hi - thanks for the great work and sharing the code.
I am new to docker and i'm finding it difficult to understand how to exactly reproduce the code and results on windows.
Could you please provide a more detailed Readme with step by step actions to take to recreate the work on windows?

**Comment by mkardas** [comment]
Hi,

as noted in https://github.com/paperswithcode/axcell/issues/19#issuecomment-822712863 AxCell does not work on Windows out of the box. You don't need to know a lot about docker to run AxCell. The steps on a Linux machine are:
 - configure docker to run without sudo, see https://docs.docker.com/engine/install/linux-postinstall/
 - run `scripts/pull_docker_images.sh`
 - run `docker-compose up -d`
The last step uses `docker-compose` that is installed as part of the conda environment. You need to install docker manually (see https://docs.docker.com/engine/install/).

**Comment by purnasrivatsa96** [comment]
Thanks!
