### ISSUE TITLE
Estimated Cost for Using AWS API

### ISSUE THREAD

**Issue by fishiu** [paperswithcode/axcell#24]
Hi,

Have you calculated the number about the cost if I use the S3 API provided by AWS to download all the related paper resources? As AWS seems charge downloading by data size so I cannot have no idea of an approximate number for the cost.

**Comment by mkardas** [comment]
Hey,

the cost depends on availability zone you run the scripts from. The data size is around 2.5 TB:

```shell
aws s3 ls --request-payer requester s3://arxiv/src/ | awk '{ sum += $3 } END { print(sum) / 1024 ** 4 }'
2.28716
```

**Comment by fishiu** [comment]
Thanks for your reply! It is really a big dataset... I wonder if there is other ways to access this dataset (especially the latex source code)? It is hard for me to afford this and actually, I only need the table data included in latex source code, which makes it not cost-efficient to download the whole huge dataset.

**Comment by mkardas** [comment]
I'm not aware of such a dataset. There are other projects that use LaTeXML to convert arXiv papers to HTML, f.e., https://www.arxiv-vanity.com/ and https://ar5iv.org/.
